application: placingliterature
version: aug2014b
runtime: python27
api_version: 1
threadsafe: yes

skip_files:
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
# - ^(.*/)?.*\.coffee
# - ^(.*/)?.*\.scss
- ^utils/*

builtins:
- deferred: on
- remote_api: on

handlers:
- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: favicon\.ico

- url: /img
  static_dir: static/images

- url: /css
  static_dir: static/styles

- url: /js
  static_dir: static/scripts

- url: /pages
  static_dir: static/pages

- url: /media
  static_dir: static/media

- url: /desktop/scripts
  static_dir: static/app/scripts

- url: /desktop/views
  static_dir: static/app/views

- url: /desktop/styles
  static_dir: static/app/styles

- url: /about
  script: handlers.home.app

- url: /funding
  script: handlers.home.app

- url: /home
  script: handlers.home.app

- url: /desktop/(.*)
  script: handlers.home.app

- url: /map(/?.*)
  script: handlers.home.app

- url: /all
  script: handlers.home.app
  login: admin

- url: /places/add
  script: handlers.new_scene.app

- url: /places/show
  script: handlers.places.app

- url: /places/info/(.*)
  script: handlers.places.app

- url: /places/visit/(.*)
  script: handlers.places.app

- url: /places/export
  script: handlers.places.app
  login: admin

- url: /places/recent
  script: handlers.places.app

- url: /places/allbydate
  script: handlers.places.app
  login: admin

- url: /places/count
  script: handlers.places.app

- url: /places/authors
  script: handlers.places.app

- url: /places/titles
  script: handlers.places.app

- url: /places/dump
  script: handlers.export.app
  login: admin

- url: /places/import
  script: handlers.export.app

- url: /places/csv_import/(.*)
  script: handlers.export.app
  login: admin

- url: /places/missing_books
  script: handlers.export.app

- url: /blog/update
  script: handlers.blogposts.app
  login: admin

- url: /user/status
  script: handlers.home.app

- url: /places/query/(.*)
  script: handlers.places.app

- url: /place/(.*)
  script: handlers.place.app

- url: /isbndb/book_import
  script: handlers.isbn.app

- url: /isbndb/author_update
  script: handlers.isbn.app
  login: admin

- url: /update_books
  script: handlers.update_scenes.app
  login: admin

- url: /update_isbns
  script: handlers.update_scenes.app
  login: admin

- url: /reset_isbns
  script: handlers.update_scenes.app
  login: admin

- url: /collections/users
  script: handlers.collections.app
  login: admin

- url: /admin/menu
  script: handlers.home.app
  login: admin

- url: /admin/edit/(.*)
  script: handlers.home.app
  login: admin

- url: /collections/(.*)
  script: handlers.collections.app

- url: /users/scenes
  script: handlers.export.app

- url: /photos/panoramio/(.*)
  script: handlers.panoramio.app
  login: admin

- url: /update_authors
  script: handlers.may_updates.app
  login: admin

- url: /update_titles
  script: handlers.may_updates.app
  login: admin

- url: /location_index/(.*)
  script: handlers.location_index.app

- url: /places/near
  script: handlers.location_index.app

- url: /places/latest
  script: handlers.location_index.app

- url: .*
  script: handlers.home.app

libraries:
- name: webapp2
  version: "2.5.1"
